apiVersion: v1
baseDomain: devcluster.openshift.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 1

metadata:
  name: $CLUSTER_NAME

platform:
  aws:
    region: $AWS_REGION
    # vpcID: $VPC_ID
    subnets:
      - $PRIVATE_SUBNET1_ID
      - $PRIVATE_SUBNET2_ID
      - $PRIVATE_SUBNET3_ID
      - $PUBLIC_SUBNET1_ID
      - $PUBLIC_SUBNET2_ID
      - $PUBLIC_SUBNET3_ID

publish: External
pullSecret: '$PULL_SECRET'
sshKey: $SSH_KEY