apiVersion: v1
baseDomain: devcluster.openshift.com
metadata:
  name: $CLUSTER_NAME
platform:
  aws:
    region: $AWS_REGION
    propagateUserTags: true
    userTags:
      cluster_name: $CLUSTER_NAME
      Environment: cluster
publish: External
pullSecret: '$PULL_SECRET'
sshKey: |
  $SSH_KEY
