apiVersion: v1
baseDomain: devcluster.openshift.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
- name: edge
  architecture: amd64
  hyperthreading: Enabled  
  replicas: 10
  platform:   
   aws:
     zones:
      - us-east-1-iah-2a
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3

metadata:
  name: $CLUSTER_NAME

platform:
  aws:
    region: $AWS_REGION

publish: External
pullSecret: '$PULL_SECRET'
sshKey: $SSH_KEY
