apiVersion: v1
baseDomain: devcluster.openshift.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3

metadata:
  name: lab-aws-custom-vpc

platform:
  aws:
    region: 
    subnets:
      - 
      - 
      - 

publish: External
pullSecret: ''
sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDqulxF0xj6CZe8fK6VqKhh+VcyhRHAOXsBdQkV5gqDvCMYL2iI+zR79HY6Pf0zn/6A+NXIzDu8VOngNnBOQSdN2zQu43Hz9Le1vRTztBfnhv2+TZYXmG2Cww43hJH46vIu4ccWRwS9GCzlnMUoIiQ3Sz2FVAtfkXT7+vG4sgsWSxkh8w9OaSXH71i+MMDZQfkKSKv48TMwFa8ztZi0MTsat28u1GVmy1KPkn/QyICLZ08EfXstrJx3rvFq5FNcTKMfvmaVZoeJSz9Wjw3zEwYQcBli0332vstEnquZg08Jbl9Poz6Gq5MQIkjw8Diq3NFi2o66aDmF4CuIkKEfIR60VFCfhbTv5ldhvttkcGCbxhWKuNhdQo7hwIICH1ihtp4xcOrwZHtCHo0mU/1L5II4SDziH4tEujcbGycgMt+oX4IuOaaatxfBdiU8MnmfT+omMsDQpZnRy12rcZFAhhw+9VhFN+nmrCDnLRgsdtT7rwtrepggrbFg2FeFs/pVU0s= faermanj@fedora