apiVersion: v1
baseDomain: devcluster.openshift.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3

metadata:
  name: lab-aws-custom-vpc

platform:
  aws:
    region: us-east-1
    subnets:
      # Private Subnets
      - subnet-0aa5db5d70814f4de
      - subnet-0d5330de6c8018d00
      - subnet-0f121a08f48f24808
      # Public Subnets
      - subnet-0aa5db5d70814f4de
      - subnet-03a5e1baa4dbeae26
      - subnet-0f5be8fed4b56a2d0

publish: External
pullSecret: '    {"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYzZiMjdhMjA5MzI1NDY4ZGEyNGNhNmU1ZmE4MGQwOTg6U0pYRDQ2R05MN0Y5VFAxN1lIMjBIM1RQRDJaMUNZVU5ZUUJHS0tJMzA2M0FROUU1RVc0QTFLUldNUTRFVVUwNQ==","email":"jufaerma@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYzZiMjdhMjA5MzI1NDY4ZGEyNGNhNmU1ZmE4MGQwOTg6U0pYRDQ2R05MN0Y5VFAxN1lIMjBIM1RQRDJaMUNZVU5ZUUJHS0tJMzA2M0FROUU1RVc0QTFLUldNUTRFVVUwNQ==","email":"jufaerma@redhat.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWVlZDUyZjc1LTkyMGQtNDhjMy1iM2VhLTNkNGFlOTM2ODBjMzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdPR1V6TXpGa1pqRTNaRFkwTVRsa1lUSmpNMlk1TUdFeE1qQmlORFUzWVNKOS5aeS1RWk83TV9uV3daSHQ4STJpck5uMkFob0ZyU1g0SnBsc1lMcV92T2NDLWYyN1VscTN6NkhzN0xwN3dfWlQ2R05oaHZVc3R0eFk4aTd3eFlwNnZGcEJrelgxOFlFc01Mc3l6Wnl5TGl0YmYtU2E5VHZ6M1pmYnBSVmVGTXlxcVBpRnhLR21fNW10ZTd6dlBIcHRHYl9FQTlBbU5XMnpQQ3gtVE1rTTl6bGhwZ2NGcTF3NWhqdVlqRzN3alhqa0RoZjZ5Wmd5dUs1LWFKNzdwTGtnMVFBRG4xM2MxWHhRQ0xkVkNFSU1tTG55STlyZlNWX1FuSk1Lekp3MHdRbTBLdThRT2NHX2xMb0lfbW12MVZfSFQyX0NRTno0ZVp0VnM1UG80am0zUEtYblRodjVKanRBQ2tKbVdHdXlZUjU5YmJTMGx3al9UVHE0Z2ZCYkt1bWx5MDFaZnJnOXZaRHdCbWRjZ2wzT2F4Q2NuX3BlblZ2TnJTT3JqOXhheGN2VEs3dkg2OUFhenpkdEx6UTNfU0l4R1lzLWVlMkMyMl9EdTUwQXA2Y1dkY09XSzZTUDlqSERKRjV5SW1PeXRBY1NJem9nTFhHZFRSQ3BmZUJFWlZGVnNFbUZ2X29DV3ZQUFdGek5HdWRoRTdWY2FhX2RCT0o0c21MaTY5SkRieEtISUw1bHRQNlI2cGxWTGpma1N2WkRMNzFvVmo4bnhrMkxSVjcxbVBxUFhoRTFkaGgtdVBTM1FKeW02aWQ5SUdqMHZncDFFYnBrSXJuOTdxY1BSMFhaWFQ5WkdkQ19qdGlVbW5mcGVPQVdxOXpmcmlpWk5UZ2VJbU56aVdkVWNJLVBldWZaMHhNNkxwTFVZVlIwNG15UlBqZTNmNHlZUXpfLTB1V0dzMkJVdEtqWQ==","email":"jufaerma@redhat.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWVlZDUyZjc1LTkyMGQtNDhjMy1iM2VhLTNkNGFlOTM2ODBjMzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdPR1V6TXpGa1pqRTNaRFkwTVRsa1lUSmpNMlk1TUdFeE1qQmlORFUzWVNKOS5aeS1RWk83TV9uV3daSHQ4STJpck5uMkFob0ZyU1g0SnBsc1lMcV92T2NDLWYyN1VscTN6NkhzN0xwN3dfWlQ2R05oaHZVc3R0eFk4aTd3eFlwNnZGcEJrelgxOFlFc01Mc3l6Wnl5TGl0YmYtU2E5VHZ6M1pmYnBSVmVGTXlxcVBpRnhLR21fNW10ZTd6dlBIcHRHYl9FQTlBbU5XMnpQQ3gtVE1rTTl6bGhwZ2NGcTF3NWhqdVlqRzN3alhqa0RoZjZ5Wmd5dUs1LWFKNzdwTGtnMVFBRG4xM2MxWHhRQ0xkVkNFSU1tTG55STlyZlNWX1FuSk1Lekp3MHdRbTBLdThRT2NHX2xMb0lfbW12MVZfSFQyX0NRTno0ZVp0VnM1UG80am0zUEtYblRodjVKanRBQ2tKbVdHdXlZUjU5YmJTMGx3al9UVHE0Z2ZCYkt1bWx5MDFaZnJnOXZaRHdCbWRjZ2wzT2F4Q2NuX3BlblZ2TnJTT3JqOXhheGN2VEs3dkg2OUFhenpkdEx6UTNfU0l4R1lzLWVlMkMyMl9EdTUwQXA2Y1dkY09XSzZTUDlqSERKRjV5SW1PeXRBY1NJem9nTFhHZFRSQ3BmZUJFWlZGVnNFbUZ2X29DV3ZQUFdGek5HdWRoRTdWY2FhX2RCT0o0c21MaTY5SkRieEtISUw1bHRQNlI2cGxWTGpma1N2WkRMNzFvVmo4bnhrMkxSVjcxbVBxUFhoRTFkaGgtdVBTM1FKeW02aWQ5SUdqMHZncDFFYnBrSXJuOTdxY1BSMFhaWFQ5WkdkQ19qdGlVbW5mcGVPQVdxOXpmcmlpWk5UZ2VJbU56aVdkVWNJLVBldWZaMHhNNkxwTFVZVlIwNG15UlBqZTNmNHlZUXpfLTB1V0dzMkJVdEtqWQ==","email":"jufaerma@redhat.com"}}}'
sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDqulxF0xj6CZe8fK6VqKhh+VcyhRHAOXsBdQkV5gqDvCMYL2iI+zR79HY6Pf0zn/6A+NXIzDu8VOngNnBOQSdN2zQu43Hz9Le1vRTztBfnhv2+TZYXmG2Cww43hJH46vIu4ccWRwS9GCzlnMUoIiQ3Sz2FVAtfkXT7+vG4sgsWSxkh8w9OaSXH71i+MMDZQfkKSKv48TMwFa8ztZi0MTsat28u1GVmy1KPkn/QyICLZ08EfXstrJx3rvFq5FNcTKMfvmaVZoeJSz9Wjw3zEwYQcBli0332vstEnquZg08Jbl9Poz6Gq5MQIkjw8Diq3NFi2o66aDmF4CuIkKEfIR60VFCfhbTv5ldhvttkcGCbxhWKuNhdQo7hwIICH1ihtp4xcOrwZHtCHo0mU/1L5II4SDziH4tEujcbGycgMt+oX4IuOaaatxfBdiU8MnmfT+omMsDQpZnRy12rcZFAhhw+9VhFN+nmrCDnLRgsdtT7rwtrepggrbFg2FeFs/pVU0s= faermanj@fedora