# gitpod.io/#github.com/CaravanaCloud/red-pod
image:
  file: .gitpod.Containerfile

tasks:
  - name: Welcome to OpenShift Solutions Lab
    init: |
      ./download-clients.sh
      echo "Solutions lab intialized at $(date)"
    command: |
      echo "Solutions lab started at $(date)"

ports:
  - port: 8080
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - redhat.java
    - ms-azuretools.vscode-docker
    - ms-python.python
    - esbenp.prettier-vscode

